
TRANSLATIONS = {
    "fr": {
        "title": "Zelda Multi-Launcher",
        "header_title": "ZELDA HUB",
        "header_subtitle": "MULTI-LAUNCHER • ARCHIPELAGO • TRACKER",
        "port_label": "Port AP:",
        "ok_btn": "OK",
        "quick_switcher_btn": "Selection Rapide",
        "config_btn": "⚙️ Config",
        "manage_controllers_btn": "🎮 Gérer les Manettes",
        "quit_game_btn": "⏹️ Quitter le Jeu (Propre)",
        "auto_config_label": "Configuration automatique des manettes",
        "auto_save_label": "Auto-Save State au changement de jeu",
        "toggle_auto_save": "AUTO-SAVE",
        "toggle_broadcast": "BROADCAST",
        "toggle_hot_swap": "HOT-SWAP",
        "opt_enable_broadcast_main": "Lancement auto du Broadcast",
        "status_ready": "Ready",
        "status_launching": "Lancement de {name}...",
        "status_playing": "En cours : {name}",
        "status_failed": "Échec : {name}",
        "status_stopping": "Arrêt de {name}...",
        "qs_busy": "LANCEMENT EN COURS...",
        "qs_title": "SÉLECTION RAPIDE",
        "msg_shortcut_enabled": "[Launcher] Raccourcis activés.",
        "msg_keyboard_missing": "Le module 'keyboard' est manquant. Le Quick Switcher ne fonctionnera pas.",
        "setup_title": "Configuration du Zelda Hub",
        "tab_emulators": "Émulateurs",
        "tab_roms": "ROMs / Jeux",
        "tab_archipelago": "Archipelago",
        "tab_slots": "Slots",
        "tab_poptracker": "PopTracker",
        "tab_obs": "OBS",
        "tab_visibility": "Visibilité UI",
        "tab_general": "Général",
        "btn_save": "Sauvegarder & Quitter",
        "btn_reset": "Réinitialiser tout",
        "btn_browse": "Parcourir...",
        "lbl_language": "Langue :",
        
        # Controller UI
        "ctrl_title": "Gestion des Manettes",
        "hub_shortcut_frame": " Raccourci Global Hub ",
        "hub_shortcut_label": "Bouton pour ouvrir le Hub:",
        "hub_shortcut_hint": "(ex: CAPTURE, GUIDE, START, BTN_15...)",
        "assign_btn": "Assigner",
        "listening_btn": "Poussez...",
        "ctrl_header": "Configuration des Manettes",
        "active_profile_lbl": "Profil Actif :",
        "save_apply_btn": "Sauvegarder et Appliquer",
        "detected_ctrls_frame": " Manettes Détectées ",
        "searching_devs": "Recherche de peripheriques...",
        "no_devs_found": "Aucune manette detectee.",
        "live_vis_frame": " Visualisation en Direct ",
        "test_profiles_frame": " Test des Profils (Inputs traduits) ",
        "mapping_tab_frame": " Mapping du Profil Actif ",
        "logical_action_col": "Action Logique",
        "physical_input_col": "Bouton Physique",
        "mapping_status_select": "Sélectionnez une action à remapper.",
        "listening_mode_btn": "Assigner (Mode Écoute)",
        "remove_mapping_btn": "Supprimer Mapping",
        "save_profile_btn": "Sauvegarder le Profil",
        "listening_for": "En écoute pour: {action}... Appuyez sur une touche.",
        "assigned_msg": "Assigné: {action} = {input_id}",
        "mapping_removed": "Mapping supprimé pour {action}",
        "save_success": "Profil et raccourci Hub sauvegardés avec succès.",
        "export_success": "Configuration sauvegardée et exportée !\n\nNouveau raccourci Hub: {hub_btn}",
        "export_fail": "Impossible d'exporter la config. Vérifiez qu'une manette est connectée.",
        
        # Setup UI Sections
        "sec_emus": "LOCALISATION DES EXÉCUTABLES",
        "sec_roms": "ROMS & FICHIERS DE JEU",
        "sec_net": "PARAMÈTRES RÉSEAU",
        "sec_slots": "NOMS DES SLOTS PAR JEU",
        "sec_tracker_global": "OPTIONS GLOBALES",
        "sec_tracker_packs": "PACKS DE TRACKING POPTRACKER",
        "sec_obs_global": "REGLAGES OBS",
        "sec_obs_scenes": "SCÈNES OBS PAR JEU",
        "sec_visibility": "AFFICHAGE DES JEUX",
        "opt_maximize_tracker": "Maximiser automatiquement le tracker au lancement",
        "opt_tracker_monitor": "Écran de lancement (Tracker) :",
        "opt_show_game": "Afficher {name}",
        "lbl_host": "Hôte (Host)",
        "lbl_port": "Port",
        "lbl_password": "Mot de passe",
        "lbl_emu_archipelago": "Dossier Archipelago",
        "lbl_emu_bizhawk": "BizHawk (EmuHawk.exe)",
        "lbl_emu_dolphin": "Dolphin (Dolphin.exe)",
        "lbl_emu_azahar": "Azahar (Azahar.exe)",
        "lbl_emu_poptracker": "PopTracker (poptracker.exe)",
        "lbl_emu_broadcast": "Dossier Broadcast Overlay",
        "btn_autodetect_roms": "🔍 AUTO-DÉTECTION DES ROMS",
        "btn_autodetect_trackers": "🔍 AUTO-DÉTECTION DES PACKS",
        "msg_config_saved": "Configuration sauvegardée !",
        "msg_success": "Succès",
        "msg_auto_detect_title": "Auto-Détection",
        "msg_auto_rom_result": "Détection terminée !\n{found} ROM(s) trouvée(s) et mise(s) à jour.",
        "msg_auto_tracker_result": "Détection terminée !\n{found} Pack(s) identifié(s) via manifest.json.",
        "opt_enable_obs": "Activer la synchronisation OBS",
        "lbl_obs_host": "Hôte OBS (par déf. localhost)",
        "lbl_obs_port": "Port WebSocket (par déf. 4455)",
        "lbl_obs_password": "Mot de passe WebSocket",
        "sec_broadcast": "OPTIONS DE DIFFUSION",
        "opt_poptracker_broadcast": "Ouvrir la fenêtre de Broadcast PopTracker",
        "btn_test_obs": "TESTER LA CONNEXION OBS",
        "opt_broadcast_mode": "Mode de diffusion :",
        "opt_broadcast_overlay": "Activer l'Overlay Bureau (Desktop Overlay)",
        "opt_broadcast_obs": "Activer le Serveur Web OBS (OBS Web Server)",
        "opt_broadcast_show_locations": "Afficher les Lieux (Show Locations)",
        "opt_broadcast_disable_hw_accel": "Désactiver l'accélération matérielle",
        "lbl_scene_for": "Scène pour {name}",
        "opt_enable_loading_screen": "Activer l'écran de chargement OBS",
        "lbl_loading_scene": "Nom de la scène de chargement",
        "lbl_transition_time": "Temps de transition (sec)",
        "lbl_config": "CONFIGURATION",
        "sec_shortcuts": "RACCOURCIS GLOBAUX DU HUB",
        "lbl_hub_keyboard_shortcut": "Raccourci Clavier Global :",
        "lbl_hub_controller_shortcut": "Bouton(s) Manette (Max 2) :",
        "lbl_hub_controller_name": "Manette pour détection :",
        "all_controllers_option": "Toutes les manettes",
        "hint_combo": "(ex: L3+R3 ou CAPTURE)",
        "opt_multi_game_keep_alive": "Garder les jeux ouverts en arrière-plan (Hot-Swap)"
    },
    "en": {
        "title": "Zelda Multi-Launcher",
        "header_title": "ZELDA HUB",
        "header_subtitle": "MULTI-LAUNCHER • ARCHIPELAGO • TRACKER",
        "port_label": "AP Port:",
        "ok_btn": "OK",
        "quick_switcher_btn": "Quick Switcher",
        "config_btn": "⚙️ Settings",
        "manage_controllers_btn": "🎮 Manage Controllers",
        "quit_game_btn": "⏹️ Quit Game (Clean)",
        "auto_config_label": "Automatic controller configuration",
        "auto_save_label": "Auto-Save State when switching games",
        "toggle_auto_save": "AUTO-SAVE",
        "toggle_broadcast": "BROADCAST",
        "toggle_hot_swap": "HOT-SWAP",
        "opt_enable_broadcast_main": "Auto-launch Broadcast overlay",
        "status_ready": "Ready",
        "status_launching": "Launching {name}...",
        "status_playing": "Playing: {name}",
        "status_failed": "Failed: {name}",
        "status_stopping": "Stopping {name}...",
        "qs_busy": "LAUNCHING...",
        "qs_title": "QUICK SWITCHER",
        "msg_shortcut_enabled": "[Launcher] Shortcuts enabled.",
        "msg_keyboard_missing": "The 'keyboard' module is missing. Quick Switcher will not work.",
        "setup_title": "Zelda Hub Configuration",
        "tab_emulators": "Emulators",
        "tab_roms": "ROMs / Games",
        "tab_archipelago": "Archipelago",
        "tab_slots": "Slots",
        "tab_poptracker": "PopTracker",
        "tab_obs": "OBS",
        "tab_visibility": "UI Visibility",
        "tab_general": "General",
        "btn_save": "Save & Exit",
        "btn_reset": "Reset All",
        "btn_browse": "Browse...",
        "lbl_language": "Language:",
        
        # Controller UI
        "ctrl_title": "Controller Management",
        "hub_shortcut_frame": " Global Hub Shortcut ",
        "hub_shortcut_label": "Button to open the Hub:",
        "hub_shortcut_hint": "(e.g.: CAPTURE, GUIDE, START, BTN_15...)",
        "assign_btn": "Assign",
        "listening_btn": "Listening...",
        "ctrl_header": "Controller Configuration",
        "active_profile_lbl": "Active Profile:",
        "save_apply_btn": "Save and Apply",
        "detected_ctrls_frame": " Detected Controllers ",
        "searching_devs": "Searching for devices...",
        "no_devs_found": "No controller detected.",
        "live_vis_frame": " Live Visualization ",
        "test_profiles_frame": " Profile Test (Translated Inputs) ",
        "mapping_tab_frame": " Active Profile Mapping ",
        "logical_action_col": "Logical Action",
        "physical_input_col": "Physical Button",
        "mapping_status_select": "Select an action to remap.",
        "listening_mode_btn": "Assign (Listen Mode)",
        "remove_mapping_btn": "Remove Mapping",
        "save_profile_btn": "Save Profile",
        "listening_for": "Listening for: {action}... Press a button.",
        "assigned_msg": "Assigned: {action} = {input_id}",
        "mapping_removed": "Mapping removed for {action}",
        "save_success": "Profile and Hub shortcut saved successfully.",
        "export_success": "Configuration saved and exported!\n\nNew Hub shortcut: {hub_btn}",
        "export_fail": "Could not export config. Verify a controller is connected.",

        # Setup UI Sections
        "sec_emus": "EXECUTABLES LOCATION",
        "sec_roms": "ROMS & GAME FILES",
        "sec_net": "NETWORK SETTINGS",
        "sec_slots": "SLOT NAMES PER GAME",
        "sec_tracker_global": "GLOBAL OPTIONS",
        "sec_tracker_packs": "POPTRACKER TRACKING PACKS",
        "sec_obs_global": "OBS SETTINGS",
        "sec_obs_scenes": "OBS SCENES PER GAME",
        "sec_visibility": "GAME VISIBILITY",
        "opt_maximize_tracker": "Automatically maximize tracker on launch",
        "opt_tracker_monitor": "Launch Screen (Tracker):",
        "opt_show_game": "Show {name}",
        "lbl_host": "Host",
        "lbl_port": "Port",
        "lbl_password": "Password",
        "lbl_emu_archipelago": "Archipelago Folder",
        "lbl_emu_bizhawk": "BizHawk (EmuHawk.exe)",
        "lbl_emu_dolphin": "Dolphin (Dolphin.exe)",
        "lbl_emu_azahar": "Azahar (Azahar.exe)",
        "lbl_emu_poptracker": "PopTracker (poptracker.exe)",
        "lbl_emu_broadcast": "Broadcast Overlay Folder",
        "btn_autodetect_roms": "🔍 AUTO-DETECT ROMS",
        "btn_autodetect_trackers": "🔍 AUTO-DETECT PACKS",
        "msg_config_saved": "Configuration saved !",
        "msg_success": "Success",
        "msg_auto_detect_title": "Auto-Detection",
        "msg_auto_rom_result": "Detection complete!\n{found} ROM(s) found and updated.",
        "msg_auto_tracker_result": "Detection complete!\n{found} Pack(s) identified via manifest.json.",
        "opt_enable_obs": "Enable OBS synchronization",
        "lbl_obs_host": "OBS Host (default localhost)",
        "lbl_obs_port": "WebSocket Port (default 4455)",
        "lbl_obs_password": "WebSocket Password",
        "sec_broadcast": "BROADCAST OPTIONS",
        "opt_poptracker_broadcast": "Open PopTracker Broadcast window",
        "btn_test_obs": "TEST OBS CONNECTION",
        "opt_broadcast_mode": "Broadcast Mode:",
        "opt_broadcast_overlay": "Enable Desktop Overlay",
        "opt_broadcast_obs": "Enable OBS Web Server",
        "opt_broadcast_show_locations": "Show Locations",
        "opt_broadcast_disable_hw_accel": "Disable Hardware Acceleration",
        "lbl_scene_for": "Scene for {name}",
        "opt_enable_loading_screen": "Enable OBS loading screen",
        "lbl_loading_scene": "Loading scene name",
        "lbl_transition_time": "Transition time (sec)",
        "lbl_config": "CONFIGURATION",
        "sec_shortcuts": "GLOBAL HUB SHORTCUTS",
        "lbl_hub_keyboard_shortcut": "Global Keyboard Shortcut:",
        "lbl_hub_controller_shortcut": "Gamepad Button(s) (Max 2):",
        "lbl_hub_controller_name": "Controller for detection:",
        "all_controllers_option": "All controllers",
        "hint_combo": "(e.g.: L3+R3 or CAPTURE)",
        "opt_multi_game_keep_alive": "Keep games running in background (Hot-Swap)"
    }
}

class Loc:
    _lang = "fr"
    
    @classmethod
    def set_lang(cls, lang):
        if lang in TRANSLATIONS:
            cls._lang = lang
            
    @classmethod
    def get(cls, key, **kwargs):
        text = TRANSLATIONS.get(cls._lang, TRANSLATIONS["en"]).get(key, key)
        if kwargs:
            try:
                return text.format(**kwargs)
            except:
                return text
        return text
