ScriptHost:AddWatchForCode("Split Map", "splitmap", Splitmapchange)
ScriptHost:AddWatchForCode("Broadcast", "broadcast", Broadcastchange)
ScriptHost:AddWatchForCode("HideLayout", "hidelayout", Hidefrommainmap)
ScriptHost:AddWatchForCode("APLayout", "aplayout", APLayoutchange)

ScriptHost:AddWatchForCode("Bugs Amount", "bugsamount", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount0", "bug0", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount1", "bug1", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount2", "bug2", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount3", "bug3", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount4", "bug4", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount5", "bug5", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount6", "bug6", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount7", "bug7", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount8", "bug8", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount9", "bug9", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount10", "bug10", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount11", "bug11", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount12", "bug12", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount13", "bug13", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount14", "bug14", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount15", "bug15", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount16", "bug16", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount17", "bug17", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount18", "bug18", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount19", "bug19", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount20", "bug20", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount21", "bug21", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount22", "bug22", Bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount23", "bug23", Bugsamountchange)
ScriptHost:AddOnLocationSectionChangedHandler("Bugs Amount Section", Bugsamountchange)