BASE = 2320000

ITEM_MAPPING = {
	[BASE + 23] = {"heartpiece", "consumable"},
	[BASE + 24] = {"heartcontainer", "consumable"},
	[BASE + 25] = {"p_sword", "progressive"},
	[BASE + 26] = {"ordonshield", "toggle"},
	[BASE + 27] = {"hylianshield", "toggle"},
	[BASE + 28] = {"magicarmor", "toggle"},
	[BASE + 29] = {"zoraarmor", "toggle"},
	[BASE + 30] = {"shadowcrystal", "toggle"},
	[BASE + 31] = {"p_wallet", "progressive"},
	[BASE + 32] = {"hawkeye", "toggle"},
	[BASE + 33] = {"boomerang", "toggle"},
	[BASE + 34] = {"spinner", "toggle"},
	[BASE + 35] = {"ballchain", "toggle"},
	[BASE + 36] = {"p_bow", "progressive"},
	[BASE + 37] = {"p_clawshot", "progressive"},
	[BASE + 38] = {"boots", "toggle"},
	[BASE + 39] = {"p_dominionrod", "progressive"},
	[BASE + 40] = {"lantern", "toggle"},
	[BASE + 41] = {"p_fishingrod", "progressive"},
	[BASE + 44] = {"slingshot", "toggle"},
	[BASE + 45] = {"bombbag", "consumable"},
	[BASE + 46] = {"bottle", "consumable"},
	[BASE + 47] = {"bottle", "consumable"},
	[BASE + 48] = {"bottle", "consumable"},
	[BASE + 49] = {"bottle", "consumable"},
	[BASE + 53] = {"horsecall", "toggle"},
	[BASE + 54] = {"ftsmallkey", "consumable"},
	[BASE + 55] = {"gmsmallkey", "consumable"},
	[BASE + 56] = {"ltsmallkey", "consumable"},
	[BASE + 57] = {"agsmallkey", "consumable"},
	[BASE + 58] = {"srsmallkey", "consumable"},
	[BASE + 59] = {"ttsmallkey", "consumable"},
	[BASE + 60] = {"cssmallkey", "consumable"},
	[BASE + 61] = {"ptsmallkey", "consumable"},
	[BASE + 62] = {"hcsmallkey", "consumable"},
	[BASE + 65] = {"gatekeys", "toggle"},
	[BASE + 66] = {"bckey", "toggle"},
	[BASE + 67] = {"aurusmemo", "toggle"},
	[BASE + 68] = {"asheissketch", "toggle"},
	[BASE + 69] = {"ftbigkey", "toggle"},
	[BASE + 71] = {"gmbigkey", "consumable"},
	[BASE + 70] = {"ltbigkey", "toggle"},
	[BASE + 72] = {"agbigkey", "toggle"},
	[BASE + 73] = {"srbigkey", "toggle"},
	[BASE + 74] = {"ttbigkey", "toggle"},
	[BASE + 75] = {"csbigkey", "toggle"},
	[BASE + 76] = {"ptbigkey", "toggle"},
	[BASE + 77] = {"hcbigkey", "toggle"},
	[BASE + 96] =  {"bug4", "toggle"},
	[BASE + 97] =  {"bug5", "toggle"},
	[BASE + 98] =  {"bug12", "toggle"},
	[BASE + 99] =  {"bug13", "toggle"},
	[BASE + 100] = {"bug8", "toggle"},
	[BASE + 101] = {"bug9", "toggle"},
	[BASE + 102] = {"bug20", "toggle"},
	[BASE + 103] = {"bug21", "toggle"},
	[BASE + 104] = {"bug18", "toggle"},
	[BASE + 105] = {"bug19", "toggle"},
	[BASE + 106] = {"bug10", "toggle"},
	[BASE + 107] = {"bug11", "toggle"},
	[BASE + 108] = {"bug6", "toggle"},
	[BASE + 109] = {"bug7", "toggle"},
	[BASE + 110] = {"bug14", "toggle"},
	[BASE + 111] = {"bug15", "toggle"},
	[BASE + 112] = {"bug16", "toggle"},
	[BASE + 113] = {"bug17", "toggle"},
	[BASE + 114] = {"bug22", "toggle"},
	[BASE + 115] = {"bug23", "toggle"},
	[BASE + 116] = {"bug0", "toggle"},
	[BASE + 117] = {"bug1", "toggle"},
	[BASE + 118] = {"bug2", "toggle"},
	[BASE + 119] = {"bug3", "toggle"},
	[BASE + 120] = {"mirrorshard", "consumable"},
	[BASE + 121] = {"fusedshadow", "consumable"},
	[BASE + 122] = {"hiddenskill", "consumable"},
	[BASE + 123] = {"skybook", "consumable"},
	[BASE + 124] = {"poesoul", "consumable"},
	[BASE + 129] = {"pumpkin", "toggle"},
	[BASE + 130] = {"cheese", "toggle"},
	[BASE + 131] = {"trapsamount", "consumable"},
	[BASE + 133] = {"giantbombs", "toggle"}
}

BUGS_ARRAY = {
		{"@Castle Town/Agitha's Castle/Male Ant", "bug0"},
		{"@Castle Town/Agitha's Castle/Female Ant", "bug1"},
		{"@Castle Town/Agitha's Castle/Male Dayfly", "bug2"},
		{"@Castle Town/Agitha's Castle/Female Dayfly", "bug3"},
		{"@Castle Town/Agitha's Castle/Male Beetle", "bug4"},
		{"@Castle Town/Agitha's Castle/Female Beetle", "bug5"},
		{"@Castle Town/Agitha's Castle/Male Mantis", "bug6"},
		{"@Castle Town/Agitha's Castle/Female Mantis", "bug7"},
		{"@Castle Town/Agitha's Castle/Male Stag Beetle", "bug8"},
		{"@Castle Town/Agitha's Castle/Female Stag Beetle", "bug9"},
		{"@Castle Town/Agitha's Castle/Male Pillbug", "bug10"},
		{"@Castle Town/Agitha's Castle/Female Pillbug", "bug11"},
		{"@Castle Town/Agitha's Castle/Male Butterfly", "bug12"},
		{"@Castle Town/Agitha's Castle/Female Butterfly", "bug13"},
		{"@Castle Town/Agitha's Castle/Male Ladybug", "bug14"},
		{"@Castle Town/Agitha's Castle/Female Ladybug", "bug15"},
		{"@Castle Town/Agitha's Castle/Male Snail", "bug16"},
		{"@Castle Town/Agitha's Castle/Female Snail", "bug17"},
		{"@Castle Town/Agitha's Castle/Male Phasmid", "bug18"},
		{"@Castle Town/Agitha's Castle/Female Phasmid", "bug19"},
		{"@Castle Town/Agitha's Castle/Male Grasshopper", "bug20"},
		{"@Castle Town/Agitha's Castle/Female Grasshopper", "bug21"},
		{"@Castle Town/Agitha's Castle/Male Dragonfly", "bug22"},
		{"@Castle Town/Agitha's Castle/Female Dragonfly", "bug23"}
	}