BASE = 2320000

LOCATION_MAPPING = {
	--Dungeons
	--Arbiter's Grounds Locations
	[BASE + 0] = {"@Arbiter's Grounds/1F/Big Key Chest/"},
	[BASE + 1] = {"@Arbiter's Grounds/B2/Death Sword Chest/"},
	[BASE + 2] = {"@Arbiter's Grounds/4F/Stallord Boss/Dungeon Reward"},
	[BASE + 3] = {"@Arbiter's Grounds/B1/East Lower Turnable Redead Chest/"},
	[BASE + 4] = {"@Arbiter's Grounds/Poes1F/East Turning Room Poe/"},
	[BASE + 5] = {"@Arbiter's Grounds/2F/East Upper Turnable Chest/"},
	[BASE + 6] = {"@Arbiter's Grounds/2F/East Upper Turnable Redead Chest/"},
	[BASE + 7] = {"@Arbiter's Grounds/1F/Entrance Chest/"},
	[BASE + 8] = {"@Arbiter's Grounds/2F/Ghoul Rat Room Chest/"},
	[BASE + 9] = {"@Arbiter's Grounds/Poes2F/Hidden Wall Poe/"},
	[BASE + 10] = {"@Arbiter's Grounds/B1/North Turning Room Chest/"},
	[BASE + 11] = {"@Arbiter's Grounds/B2/Spinner Room First Small Chest/"},
	[BASE + 12] = {"@Arbiter's Grounds/B2/Spinner Room Lower Central Small Chest/"},
	[BASE + 13] = {"@Arbiter's Grounds/B1/Spinner Room Lower North Chest/"},
	[BASE + 14] = {"@Arbiter's Grounds/B2/Spinner Room Second Small Chest/"},
	[BASE + 15] = {"@Arbiter's Grounds/B2/Spinner Room Stalfos Alcove Chest/"},
	[BASE + 16] = {"@Arbiter's Grounds/4F/Stallord Boss/Stallord Heart Container"},
	[BASE + 17] = {"@Arbiter's Grounds/1F/Torch Room East Chest/"},
	[BASE + 18] = {"@Arbiter's Grounds/Poes1F/Torch Room Poe/"},
	[BASE + 19] = {"@Arbiter's Grounds/1F/Torch Room West Chest/"},
	[BASE + 20] = {"@Arbiter's Grounds/1F/West Chandelier Chest/"},
	[BASE + 21] = {"@Arbiter's Grounds/Poes2F/West Poe/"},
	[BASE + 22] = {"@Arbiter's Grounds/1F/West Small Chest Behind Block/"},
	[BASE + 23] = {"@Arbiter's Grounds/1F/West Stalfos Northeast Chest/"},
	[BASE + 24] = {"@Arbiter's Grounds/1F/West Stalfos West Chest/"},
	
	--City in The Sky Locations
	[BASE + 25] = {"@City in the Sky/B3/Aeralfos Chest/"},
	[BASE + 26] = {"@City in the Sky/5F/Argorok Boss/Argorok Heart Container"},
	[BASE + 27] = {"@City in the Sky/2F/Baba Tower Alcove Chest/"},
	[BASE + 28] = {"@City in the Sky/2F/Baba Tower Narrow Ledge Chest/"},
	[BASE + 29] = {"@City in the Sky/3F/Baba Tower Top Small Chest/"},
	[BASE + 30] = {"@City in the Sky/4F/Big Key Chest/"},
	[BASE + 31] = {"@City in the Sky/4F/Central Outside Ledge Chest/"},
	[BASE + 32] = {"@City in the Sky/4F/Central Outside Poe Island Chest/"},
	[BASE + 33] = {"@City in the Sky/1F/Chest Behind North Fan/"},
	[BASE + 34] = {"@City in the Sky/3F/Chest Below Big Key Chest/"},
	[BASE + 35] = {"@City in the Sky/5F/Argorok Boss/Dungeon Reward"},
	[BASE + 36] = {"@City in the Sky/1F/East First Wing Chest After Fans/"},
	[BASE + 37] = {"@City in the Sky/1F/East Tile Worm Small Chest/"},
	[BASE + 38] = {"@City in the Sky/2F/East Wing After Dinalfos Alcove Chest/"},
	[BASE + 39] = {"@City in the Sky/2F/East Wing After Dinalfos Ledge Chest/"},
	[BASE + 40] = {"@City in the Sky/B1/East Wing Lower Level Chest/"},
	[BASE + 41] = {"@City in the Sky/Poes2F/Garden Island Poe/"},
	[BASE + 42] = {"@City in the Sky/Poes4F/Poe Above Central Fan/"},
	[BASE + 43] = {"@City in the Sky/1F/Underwater East Chest/"},
	[BASE + 44] = {"@City in the Sky/1F/Underwater West Chest/"},
	[BASE + 45] = {"@City in the Sky/3F/West Garden Corner Chest/"},
	[BASE + 46] = {"@City in the Sky/3F/West Garden Ledge Chest/"},
	[BASE + 47] = {"@City in the Sky/2F/West Garden Lone Island Chest/"},
	[BASE + 48] = {"@City in the Sky/2F/West Garden Lower Chest/"},
	[BASE + 49] = {"@City in the Sky/B1/West Wing Baba Balcony Chest/"},
	[BASE + 50] = {"@City in the Sky/1F/West Wing First Chest/"},
	[BASE + 51] = {"@City in the Sky/1F/West Wing Narrow Ledge Chest/"},
	[BASE + 52] = {"@City in the Sky/1F/West Wing Tile Worm Chest/"},
	
	--Forest Temple Locations
	[BASE + 53] = {"@Forest Temple/1F/Big Baba Key/"},
	[BASE + 54] = {"@Forest Temple/1F/Big Key Chest/"},
	[BASE + 55] = {"@Forest Temple/1F/Central Chest Behind Stairs/"},
	[BASE + 56] = {"@Forest Temple/1F/Central Chest Hanging From Web/"},
	[BASE + 57] = {"@Forest Temple/1F/Central North Chest/"},
	[BASE + 58] = {"@Forest Temple/1F/Diababa Boss/Diababa Heart Container"},
	[BASE + 59] = {"@Forest Temple/1F/Diababa Boss/Dungeon Reward"},
	[BASE + 60] = {"@Forest Temple/1F/East Tile Worm Chest/"},
	[BASE + 61] = {"@Forest Temple/1F/East Water Cave Chest/"},
	[BASE + 62] = {"@Forest Temple/1F/Entrance Vines Chest/"},
	[BASE + 63] = {"@Forest Temple/1F/Gale Boomerang/"},
	[BASE + 64] = {"@Forest Temple/1F/North Deku Like Chest/"},
	[BASE + 65] = {"@Forest Temple/1F/Second Monkey Under Bridge Chest/"},
	[BASE + 66] = {"@Forest Temple/1F/Totem Pole Chest/"},
	[BASE + 67] = {"@Forest Temple/1F/West Deku Like Chest/"},
	[BASE + 68] = {"@Forest Temple/1F/West Tile Worm Chest Behind Stairs/"},
	[BASE + 69] = {"@Forest Temple/1F/West Tile Worm Room Vines Chest/"},
	[BASE + 70] = {"@Forest Temple/1F/Windless Bridge Chest/"},
	
	--Goron Mines Locations
	[BASE + 71] = {"@Goron Mines/2F/After Crystal Switch Room Magnet Wall Chest/"},
	[BASE + 72] = {"@Goron Mines/2F/Beamos Room Chest/"},
	[BASE + 73] = {"@Goron Mines/2F/Chest Before Dangoro/"},
	[BASE + 74] = {"@Goron Mines/2F/Crystal Switch Room Small Chest/"},
	[BASE + 75] = {"@Goron Mines/2F/Crystal Switch Room Underwater Chest/"},
	[BASE + 76] = {"@Goron Mines/2F/Dangoro Chest/"},
	[BASE + 77] = {"@Goron Mines/2F/Fyrus Boss/Dungeon Reward"},
	[BASE + 78] = {"@Goron Mines/1F/Entrance Chest/"},
	[BASE + 79] = {"@Goron Mines/2F/Fyrus Boss/Fyrus Heart Container"},
	[BASE + 80] = {"@Goron Mines/1F/Gor Amato Chest/"},
	[BASE + 81] = {"@Goron Mines/1F/Gor Amato Key Shard/"},
	[BASE + 82] = {"@Goron Mines/1F/Gor Amato Small Chest/"},
	[BASE + 83] = {"@Goron Mines/2F/Gor Ebizo Chest/"},
	[BASE + 84] = {"@Goron Mines/2F/Gor Ebizo Key Shard/"},
	[BASE + 85] = {"@Goron Mines/2F/Gor Liggs Chest/"},
	[BASE + 86] = {"@Goron Mines/2F/Gor Liggs Key Shard/"},
	[BASE + 87] = {"@Goron Mines/1F/Magnet Maze Chest/"},
	[BASE + 88] = {"@Goron Mines/1F/Main Magnet Room Bottom Chest/"},
	[BASE + 89] = {"@Goron Mines/2F/Main Magnet Room Top Chest/"},
	[BASE + 90] = {"@Goron Mines/2F/Outside Beamos Chest/"},
	[BASE + 91] = {"@Goron Mines/2F/Outside Clawshot Chest/"},
	[BASE + 92] = {"@Goron Mines/2F/Outside Underwater Chest/"},
	
	--Hyrule Castle Locations
	[BASE + 93] = {"@Hyrule Castle/2F/Big Key Chest/"},
	[BASE + 94] = {"@Hyrule Castle/2F/East Wing Balcony Chest/"},
	[BASE + 95] = {"@Hyrule Castle/1F/East Wing Boomerang Puzzle Chest/"},
	[BASE + 96] = {"@Hyrule Castle/1F/Graveyard Switch Room/Back Left Chest"},
	[BASE + 97] = {"@Hyrule Castle/1F/Graveyard Switch Room/Front Left Chest"},
	[BASE + 98] = {"@Hyrule Castle/1F/Graveyard Switch Room/Right Chest"},
	[BASE + 99] = {"@Hyrule Castle/1F/Graveyard Owl Statue Chest/"},
	[BASE + 100] = {"@Hyrule Castle/1F/King Bulblin Key/"},
	[BASE + 101] = {"@Hyrule Castle/2F/Lantern Staircase Chest/"},
	[BASE + 102] = {"@Hyrule Castle/2F/Main Hall Northeast Chest/"},
	[BASE + 103] = {"@Hyrule Castle/2F/Main Hall Northwest Chest/"},
	[BASE + 104] = {"@Hyrule Castle/2F/Main Hall Southwest Chest/"},
	[BASE + 105] = {"@Hyrule Castle/2F/Southeast Balcony Tower Chest/"},
	[BASE + 106] = {"@Hyrule Castle/4F/Treasure Room/Eighth Small Chest"},
	[BASE + 107] = {"@Hyrule Castle/4F/Treasure Room/Fifth Chest"},
	[BASE + 108] = {"@Hyrule Castle/4F/Treasure Room/Fifth Small Chest"},
	[BASE + 109] = {"@Hyrule Castle/4F/Treasure Room/First Chest"},
	[BASE + 110] = {"@Hyrule Castle/4F/Treasure Room/First Small Chest"},
	[BASE + 111] = {"@Hyrule Castle/4F/Treasure Room/Fourth Chest"},
	[BASE + 112] = {"@Hyrule Castle/4F/Treasure Room/Fourth Small Chest"},
	[BASE + 113] = {"@Hyrule Castle/4F/Treasure Room/Second Chest"},
	[BASE + 114] = {"@Hyrule Castle/4F/Treasure Room/Second Small Chest"},
	[BASE + 115] = {"@Hyrule Castle/4F/Treasure Room/Seventh Small Chest"},
	[BASE + 116] = {"@Hyrule Castle/4F/Treasure Room/Sixth Small Chest"},
	[BASE + 117] = {"@Hyrule Castle/4F/Treasure Room/Third Chest"},
	[BASE + 118] = {"@Hyrule Castle/4F/Treasure Room/Third Small Chest"},
	[BASE + 119] = {"@Hyrule Castle/1F/West Courtyard Central Small Chest/"},
	[BASE + 120] = {"@Hyrule Castle/1F/West Courtyard North Small Chest/"},
	
	--Lakebed Temple Locations
	[BASE + 121] = {"@Lakebed Temple/1F/Before Deku Toad Alcove Chest/"},
	[BASE + 122] = {"@Lakebed Temple/B1/Before Deku Toad Underwater Left Chest/"},
	[BASE + 123] = {"@Lakebed Temple/B1/Before Deku Toad Underwater Right Chest/"},
	[BASE + 124] = {"@Lakebed Temple/B1/Big Key Chest/"},
	[BASE + 125] = {"@Lakebed Temple/1F/Central Room Chest/"},
	[BASE + 126] = {"@Lakebed Temple/1F/Central Room Small Chest/"},
	[BASE + 127] = {"@Lakebed Temple/B1/Central Room Spire Chest/"},
	[BASE + 128] = {"@Lakebed Temple/2F/Chandelier Chest/"},
	[BASE + 129] = {"@Lakebed Temple/1F/Deku Toad Chest/"},
	[BASE + 130] = {"@Lakebed Temple/B2/Morpheel Boss/Dungeon Reward"},
	[BASE + 131] = {"@Lakebed Temple/B1/East Lower Waterwheel Bridge Chest/"},
	[BASE + 132] = {"@Lakebed Temple/B1/East Lower Waterwheel Stalactite Chest/"},
	[BASE + 133] = {"@Lakebed Temple/2F/East Second Floor Southeast Chest/"},
	[BASE + 134] = {"@Lakebed Temple/2F/East Second Floor Southwest Chest/"},
	[BASE + 135] = {"@Lakebed Temple/4F/East Water Supply Clawshot Chest/"},
	[BASE + 136] = {"@Lakebed Temple/4F/East Water Supply Small Chest/"},
	[BASE + 137] = {"@Lakebed Temple/2F/Lobby Left Chest/"},
	[BASE + 138] = {"@Lakebed Temple/2F/Lobby Rear Chest/"},
	[BASE + 139] = {"@Lakebed Temple/B2/Morpheel Boss/Morpheel Heart Container"},
	[BASE + 140] = {"@Lakebed Temple/2F/Stalactite Room Chest/"},
	[BASE + 141] = {"@Lakebed Temple/1F/Underwater Maze Small Chest/"},
	[BASE + 142] = {"@Lakebed Temple/1F/West Lower Small Chest/"},
	[BASE + 143] = {"@Lakebed Temple/2F/West Second Floor Central Small Chest/"},
	[BASE + 144] = {"@Lakebed Temple/2F/West Second Floor Northeast Chest/"},
	[BASE + 145] = {"@Lakebed Temple/2F/West Second Floor Southeast Chest/"},
	[BASE + 146] = {"@Lakebed Temple/2F/West Second Floor Southwest Underwater Chest/"},
	[BASE + 147] = {"@Lakebed Temple/4F/West Water Supply Chest/"},
	[BASE + 148] = {"@Lakebed Temple/4F/West Water Supply Small Chest/"},
	
	--Palace of Twilight Locations
	[BASE + 149] = {"@Palace of Twilight/3F/Big Key Chest/"},
	[BASE + 150] = {"@Palace of Twilight/2F/Central First Room Chest/"},
	[BASE + 151] = {"@Palace of Twilight/3F/Central Outdoor Chest/"},
	[BASE + 152] = {"@Palace of Twilight/3F/Central Tower Chest/"},
	[BASE + 153] = {"@Palace of Twilight/1F/Collect Both Sols/"},
	[BASE + 154] = {"@Palace of Twilight/1F/East Wing First Room East Alcove Chest/"},
	[BASE + 155] = {"@Palace of Twilight/1F/East Wing First Room North Small Chest/"},
	[BASE + 156] = {"@Palace of Twilight/1F/East Wing First Room West Alcove Chest/"},
	[BASE + 157] = {"@Palace of Twilight/1F/East Wing First Room Zant Head Chest/"},
	[BASE + 158] = {"@Palace of Twilight/1F/East Wing Second Room Northeast Chest/"},
	[BASE + 159] = {"@Palace of Twilight/1F/East Wing Second Room Northwest Chest/"},
	[BASE + 160] = {"@Palace of Twilight/1F/East Wing Second Room Southeast Chest/"},
	[BASE + 161] = {"@Palace of Twilight/1F/East Wing Second Room Southwest Chest/"},
	[BASE + 162] = {"@Palace of Twilight/1F/West Wing Chest Behind Wall of Darkness/"},
	[BASE + 163] = {"@Palace of Twilight/1F/West Wing First Room Central Chest/"},
	[BASE + 164] = {"@Palace of Twilight/1F/West Wing Second Room Central Chest/"},
	[BASE + 165] = {"@Palace of Twilight/1F/West Wing Second Room Lower South Chest/"},
	[BASE + 166] = {"@Palace of Twilight/1F/West Wing Second Room Southeast Chest/"},
	[BASE + 167] = {"@Palace of Twilight/4F/Zant Boss/Zant Heart Container"},
	
	--Snowpeak Ruins Locations
	[BASE + 168] = {"@Snowpeak Ruins/1F/Ball and Chain/"},
	[BASE + 169] = {"@Snowpeak Ruins/3F/Blizzeta Boss/Blizzeta Heart Container"},
	[BASE + 170] = {"@Snowpeak Ruins/1F/Broken Floor Chest/"},
	[BASE + 171] = {"@Snowpeak Ruins/2F/Chapel Chest/"},
	[BASE + 172] = {"@Snowpeak Ruins/1F/Chest After Darkhammer/"},
	[BASE + 173] = {"@Snowpeak Ruins/1F/Courtyard Central Chest/"},
	[BASE + 174] = {"@Snowpeak Ruins/3F/Blizzeta Boss/Dungeon Reward"},
	[BASE + 175] = {"@Snowpeak Ruins/1F/East Courtyard Buried Chest/"},
	[BASE + 176] = {"@Snowpeak Ruins/1F/East Courtyard Chest/"},
	[BASE + 177] = {"@Snowpeak Ruins/Poes2F/Ice Room Poe/"},
	[BASE + 178] = {"@Snowpeak Ruins/Poes1F/Lobby Armor Poe/"},
	[BASE + 179] = {"@Snowpeak Ruins/2F/Lobby Chandelier Chest/"},
	[BASE + 180] = {"@Snowpeak Ruins/1F/Lobby East Armor Chest/"},
	[BASE + 181] = {"@Snowpeak Ruins/Poes1F/Lobby Poe/"},
	[BASE + 182] = {"@Snowpeak Ruins/1F/Lobby West Armor Chest/"},
	[BASE + 183] = {"@Snowpeak Ruins/1F/Mansion Map/"},
	[BASE + 184] = {"@Snowpeak Ruins/2F/Northeast Chandelier Chest/"},
	[BASE + 185] = {"@Snowpeak Ruins/1F/Ordon Pumpkin Chest/"},
	[BASE + 186] = {"@Snowpeak Ruins/1F/West Cannon Room Central Chest/"},
	[BASE + 187] = {"@Snowpeak Ruins/1F/West Cannon Room Corner Chest/"},
	[BASE + 188] = {"@Snowpeak Ruins/1F/West Courtyard Buried Chest/"},
	[BASE + 189] = {"@Snowpeak Ruins/1F/Wooden Beam Central Chest/"},
	[BASE + 190] = {"@Snowpeak Ruins/2F/Wooden Beam Chandelier Chest/"},
	[BASE + 191] = {"@Snowpeak Ruins/1F/Wooden Beam Northwest Chest/"},
	
	--Temple of Time Locations
	[BASE + 192] = {"@Temple of Time/1F/Armogohma Boss/Armogohma Heart Container"},
	[BASE + 193] = {"@Temple of Time/5F/Armos Antechamber East Chest/"},
	[BASE + 194] = {"@Temple of Time/5F/Armos Antechamber North Chest/"},
	[BASE + 195] = {"@Temple of Time/5F/Armos Antechamber Statue Chest/"},
	[BASE + 196] = {"@Temple of Time/7F/Big Key Chest/"},
	[BASE + 197] = {"@Temple of Time/8F/Chest Before Darknut/"},
	[BASE + 198] = {"@Temple of Time/8F/Darknut Chest/"},
	[BASE + 199] = {"@Temple of Time/1F/Armogohma Boss/Dungeon Reward"},
	[BASE + 200] = {"@Temple of Time/3F/First Staircase Armos Chest/"},
	[BASE + 201] = {"@Temple of Time/2F/First Staircase Gohma Gate Chest/"},
	[BASE + 202] = {"@Temple of Time/3F/First Staircase Window Chest/"},
	[BASE + 203] = {"@Temple of Time/7F/Floor Switch Puzzle Room Upper Chest/"},
	[BASE + 204] = {"@Temple of Time/7F/Gilloutine Chest/"},
	[BASE + 205] = {"@Temple of Time/1F/Lobby Lantern Chest/"},
	[BASE + 206] = {"@Temple of Time/5F/Moving Wall Beamos Room Chest/"},
	[BASE + 207] = {"@Temple of Time/5F/Moving Wall Dinalfos Room Chest/"},
	[BASE + 208] = {"@Temple of Time/Poes7F/Poe Above Scales/"},
	[BASE + 209] = {"@Temple of Time/Poes3F/Poe Behind Gate/"},
	[BASE + 210] = {"@Temple of Time/6F/Scales Gohma Chest/"},
	[BASE + 211] = {"@Temple of Time/7F/Scales Upper Chest/"},
	
	--Overworld
	--Beside Castle Town Locations
	[BASE + 445] = {"@Lanayru Region/Beside Castle Town/Helmasaur Grotto Chest/"},
	[BASE + 371] = {"@Lanayru Region/Beside Castle Town/Owl Statue/Sky Character"},
	[BASE + 370] = {"@Lanayru Region/Beside Castle Town/Owl Statue/Chest"},
	[BASE + 372] = {"@Lanayru Region/Beside Castle Town Poes/Amphitheater Poe/"},
	[BASE + 443] = {"@Lanayru Region/Beside Castle Town Bugs/Female Butterfly/"},
	[BASE + 446] = {"@Lanayru Region/Beside Castle Town Bugs/Male Butterfly/"},
	[BASE + 444] = {"@Lanayru Region/Beside Castle Town Golden Wolves/Golden Wolf/"},
	
	--Castle Town Locations
	[BASE + 359] = {"@Castle Town/Charlo Donation Blessing/"},
	[BASE + 439] = {"@Castle Town/STAR/Prize 1"},
	[BASE + 440] = {"@Castle Town/STAR/Prize 2"},
	[BASE + 358] = {"@Castle Town/Malo Mart Magic Armor/"},
	[BASE + 376] = {"@Castle Town/Jovani/20 Poe Souls"},
	[BASE + 377] = {"@Castle Town/Jovani/60 Poe Souls"},
	--[BASE + ] = {"@Castle Town/Telma Invoice/"},
	[BASE + 360] = {"@Castle Town/Doctor's Office Balcony Chest/"},
	[BASE + 345] = {"@Castle Town/Agitha's Castle/Male Ant"},
	[BASE + 333] = {"@Castle Town/Agitha's Castle/Female Ant"},
	[BASE + 348] = {"@Castle Town/Agitha's Castle/Male Dayfly"},
	[BASE + 336] = {"@Castle Town/Agitha's Castle/Female Dayfly"},
	[BASE + 346] = {"@Castle Town/Agitha's Castle/Male Beetle"},
	[BASE + 334] = {"@Castle Town/Agitha's Castle/Female Beetle"},
	[BASE + 352] = {"@Castle Town/Agitha's Castle/Male Mantis"},
	[BASE + 340] = {"@Castle Town/Agitha's Castle/Female Mantis"},
	[BASE + 356] = {"@Castle Town/Agitha's Castle/Male Stag Beetle"},
	[BASE + 344] = {"@Castle Town/Agitha's Castle/Female Stag Beetle"},
	[BASE + 354] = {"@Castle Town/Agitha's Castle/Male Pillbug"},
	[BASE + 342] = {"@Castle Town/Agitha's Castle/Female Pillbug"},
	[BASE + 347] = {"@Castle Town/Agitha's Castle/Male Butterfly"},
	[BASE + 335] = {"@Castle Town/Agitha's Castle/Female Butterfly"},
	[BASE + 351] = {"@Castle Town/Agitha's Castle/Male Ladybug"},
	[BASE + 339] = {"@Castle Town/Agitha's Castle/Female Ladybug"},
	[BASE + 355] = {"@Castle Town/Agitha's Castle/Male Snail"},
	[BASE + 343] = {"@Castle Town/Agitha's Castle/Female Snail"},
	[BASE + 353] = {"@Castle Town/Agitha's Castle/Male Phasmid"},
	[BASE + 341] = {"@Castle Town/Agitha's Castle/Female Phasmid"},
	[BASE + 350] = {"@Castle Town/Agitha's Castle/Male Grasshopper"},
	[BASE + 338] = {"@Castle Town/Agitha's Castle/Female Grasshopper"},
	[BASE + 349] = {"@Castle Town/Agitha's Castle/Male Dragonfly"},
	[BASE + 337] = {"@Castle Town/Agitha's Castle/Female Dragonfly"},
	[BASE + 378] = {"@Castle Town Poes/Jovani House Poe/"},
	[BASE + 361] = {"@Castle Town Poes/East Castle Town Bridge Poe/"},
	[BASE + 427] = {"@Castle Town Golden Wolves/Golden Wolf/"},
	
	--Death Mountain Locations
	[BASE + 218] = {"@Eldin Region/Death Mountain/Alcove Chest/"},
	[BASE + 219] = {"@Eldin Region/Death Mountain Poes/Death Mountain Trail Poe/"},
	--[BASE + ] = {"@Eldin Region/Death Mountain Golden Wolves/Ordon Spring Stone/"},
	
	--Eldin Field Locations
	[BASE + 220] = {"@Eldin Region/Eldin Field/Bomb Rock Chest/"},
	[BASE + 238] = {"@Eldin Region/Eldin Field/Goron Springwater Rush/"},
	[BASE + 222] = {"@Eldin Region/Eldin Field/Bomskit Grotto/Left Chest"},
	[BASE + 221] = {"@Eldin Region/Eldin Field/Bomskit Grotto/Lantern Chest"},
	[BASE + 228] = {"@Eldin Region/Eldin Field/Water Bomb Fish Grotto/"},
	[BASE + 215] = {"@Eldin Region/Eldin Field/Owl Statue Chest/"},
	[BASE + 224] = {"@Eldin Region/Eldin Field Bugs/Male Grasshopper/"},
	[BASE + 223] = {"@Eldin Region/Eldin Field Bugs/Female Grasshopper/"},
	[BASE + 214] = {"@Eldin Region/Eldin Field Bugs/Male Phasmid/"},
	--North Eldin Locations
	[BASE + 216] = {"@Eldin Region/Eldin Field/Owl Statue Sky Character/"},
	[BASE + 236] = {"@Eldin Region/Eldin Field/Stockcave/Upper Chest"},
	[BASE + 234] = {"@Eldin Region/Eldin Field/Stockcave/Lantern Chest"},
	[BASE + 235] = {"@Eldin Region/Eldin Field/Stockcave/Lowest Chest"},
	[BASE + 225] = {"@Eldin Region/Eldin Field/Stalfos Grotto/Left Small Chest"},
	[BASE + 226] = {"@Eldin Region/Eldin Field/Stalfos Grotto/Right Small Chest"},
	[BASE + 227] = {"@Eldin Region/Eldin Field/Stalfos Grotto/Stalfos Chest"},
	[BASE + 213] = {"@Eldin Region/Eldin Field Bugs/Female Phasmid/"},
	
	--Faron Field Locations
	[BASE + 268] = {"@Faron Region/Faron Field/Corner Grotto/Left Chest"},
	[BASE + 270] = {"@Faron Region/Faron Field/Corner Grotto/Right Chest"},
	[BASE + 269] = {"@Faron Region/Faron Field/Corner Grotto/Rear Chest"},
	[BASE + 274] = {"@Faron Region/Faron Field/Tree Heart Piece/"},
	[BASE + 267] = {"@Faron Region/Faron Field/Bridge Chest/"},
	[BASE + 273] = {"@Faron Region/Faron Field Poes/Faron Field Poe/"},
	[BASE + 272] = {"@Faron Region/Faron Field Bugs/Male Beetle/"},
	[BASE + 271] = {"@Faron Region/Faron Field Bugs/Female Beetle/"},
	
	--Faron Woods Locations
	[BASE + 266] = {"@Faron Region/Faron Woods/Coro Bottle/"},
	[BASE + 297] = {"@Faron Region/Faron Woods/South Cave Chest/"},
	[BASE + 279] = {"@Faron Region/Faron Woods/Mist - South Chest/"},
	[BASE + 280] = {"@Faron Region/Faron Woods/Mist - Stump Chest/"},
	[BASE + 277] = {"@Faron Region/Faron Woods/Mist - North Chest/"},
	[BASE + 276] = {"@Faron Region/Faron Woods/Mist - Cave/Open Chest"},
	[BASE + 275] = {"@Faron Region/Faron Woods/Mist - Cave/Lantern Chest"},
	[BASE + 281] = {"@Faron Region/Faron Woods/Golden Wolf/"},
	[BASE + 287] = {"@Faron Region/Faron Woods/Deku Baba Chest/"},
	[BASE + 282] = {"@Faron Region/Faron Woods/Owl Statue Chest/"},
	[BASE + 283] = {"@Faron Region/Faron Woods/Owl Statue Sky Character/"},
	[BASE + 278] = {"@Faron Region/Faron Woods Poes/Mist Poe/"},
	--[BASE + ] = {"@Faron Region/Faron Woods Golden Wolves/South Castle Town Stone/"},
	
	--Gerudo Desert Locations
	[BASE + 327] = {"@Gerudo Desert/Skulltula Grotto Chest/"},
	[BASE + 322] = {"@Gerudo Desert/Peahat Ledge Chest/"},
	[BASE + 310] = {"@Gerudo Desert/East Canyon Chest/"},
	[BASE + 328] = {"@Gerudo Desert/South Chest Behind Wooden Gates/"},
	[BASE + 314] = {"@Gerudo Desert/Lone Small Chest/"},
	[BASE + 320] = {"@Gerudo Desert/Owl Statue/Chest"},
	[BASE + 321] = {"@Gerudo Desert/Owl Statue/Sky Character"},
	[BASE + 306] = {"@Gerudo Desert/Cave of Ordeals/Great Fairy Reward"},
	[BASE + 329] = {"@Gerudo Desert/West Canyon Chest/"},
	[BASE + 309] = {"@Gerudo Desert/Campfire/West Chest"},
	[BASE + 307] = {"@Gerudo Desert/Campfire/East Chest"},
	[BASE + 308] = {"@Gerudo Desert/Campfire/North Chest"},
	[BASE + 319] = {"@Gerudo Desert/Northwest Chest Behind Gates/"},
	[BASE + 318] = {"@Gerudo Desert/Northeast Chest Behind Gates/"},
	[BASE + 325] = {"@Gerudo Desert/Rock Grotto/Lantern Chest"},
	[BASE + 317] = {"@Gerudo Desert/North Small Chest Before Bulblin Camp/"},
	[BASE + 298] = {"@Gerudo Desert/First Chest Under Tower At Entrance/"},
	[BASE + 302] = {"@Gerudo Desert/Bulblin Guard Key/"},
	[BASE + 301] = {"@Gerudo Desert/Small Chest in Back of Camp/"},
	[BASE + 300] = {"@Gerudo Desert/Roasted Boar/"},
	[BASE + 330] = {"@Gerudo Desert/Outside Arbiter's Grounds Lantern Chest/"},
	[BASE + 311] = {"@Gerudo Desert Poes/East Poe/"},
	[BASE + 323] = {"@Gerudo Desert Poes/Cave of Ordeals/Poe Above Cave of Ordeals"},
	[BASE + 303] = {"@Gerudo Desert Poes/Cave of Ordeals/Floor 17 Poe"},
	[BASE + 304] = {"@Gerudo Desert Poes/Cave of Ordeals/Floor 33 Poe"},
	[BASE + 305] = {"@Gerudo Desert Poes/Cave of Ordeals/Floor 44 Poe"},
	[BASE + 316] = {"@Gerudo Desert Poes/Rock Grotto/Outside - North Peahat Poe"},
	[BASE + 324] = {"@Gerudo Desert Poes/Rock Grotto/First Poe"},
	[BASE + 326] = {"@Gerudo Desert Poes/Rock Grotto/Second Poe"},
	[BASE + 332] = {"@Gerudo Desert Poes/Outside Bulblin Camp Poe/"},
	[BASE + 299] = {"@Gerudo Desert Poes/Bulblin Camp Poe/"},
	[BASE + 331] = {"@Gerudo Desert Poes/Outside Arbiter's Grounds Poe/"},
	[BASE + 315] = {"@Gerudo Desert Bugs/Male Dayfly/"},
	[BASE + 312] = {"@Gerudo Desert Bugs/Female Dayfly/"},
	[BASE + 313] = {"@Gerudo Desert Golden Wolves/Golden Wolf/"},
	
	--Hidden Village Locations
	[BASE + 217] = {"@Eldin Region/Hidden Village/Cats Hide and Seek Minigame/"},
	--[BASE + ] = {"@Eldin Region/Hidden Village/Ilia's Charm/"},
	[BASE + 264] = {"@Eldin Region/Hidden Village/Skybook From Impaz/"},
	[BASE + 239] = {"@Eldin Region/Hidden Village Poes/Hidden Village Poe/"},
	--[BASE + ] = {"@Eldin Region/Hidden Village Golden Wolves/North Castle Town Stone/"},
	
	--Kakariko Locations
	[BASE + 252] = {"@Eldin Region/Kakariko/Kakariko Inn Chest/"},
	[BASE + 233] = {"@Eldin Region/Kakariko/Eldin Spring Underwater Chest/"},
	[BASE + 253] = {"@Eldin Region/Kakariko/Bomb Rock Spire Heart Piece/"},
	[BASE + 262] = {"@Eldin Region/Kakariko/Watchtower/Chest"},
	[BASE + 265] = {"@Eldin Region/Kakariko/Watchtower/Talo Sharpshooting"},
	[BASE + 261] = {"@Eldin Region/Kakariko/Watchtower Alcove Chest/"},
	[BASE + 212] = {"@Eldin Region/Kakariko/Barnes Bomb Bag/"},
	[BASE + 257] = {"@Eldin Region/Kakariko/Malo Mart/Hylian Shield"},
	[BASE + 258] = {"@Eldin Region/Kakariko/Malo Mart/Red Potion"},
	[BASE + 259] = {"@Eldin Region/Kakariko/Malo Mart/Wooden Shield"},
	[BASE + 256] = {"@Eldin Region/Kakariko/Malo Mart/Hawkeye"},
	--[BASE + ] = {"@Eldin Region/Kakariko/Renado's Sanctuary/Renado's Letter"},
	--[BASE + ] = {"@Eldin Region/Kakariko/Renado's Sanctuary/Ilia Memory Reward"},
	[BASE + 249] = {"@Eldin Region/Kakariko/Lantern Chest/"},
	[BASE + 263] = {"@Eldin Region/Kakariko/Graveyard Spring/Rutela's Blessing"},
	[BASE + 237] = {"@Eldin Region/Kakariko/Graveyard Spring/Gift From Ralis"},
	[BASE + 254] = {"@Eldin Region/Kakariko Poes/Bomb Shop Poe/"},
	[BASE + 260] = {"@Eldin Region/Kakariko Poes/Watchtower Poe/"},
	[BASE + 251] = {"@Eldin Region/Kakariko Poes/Open Poe/"},
	[BASE + 248] = {"@Eldin Region/Kakariko Poes/Grave Poe/"},
	[BASE + 255] = {"@Eldin Region/Kakariko Bugs/Female Ant/"},
	[BASE + 250] = {"@Eldin Region/Kakariko Bugs/Male Ant/"},
	[BASE + 247] = {"@Eldin Region/Kakariko Golden Wolves/Golden Wolf/"},
	
	--Kakariko Gorge Locations
	[BASE + 229] = {"@Eldin Region/Kakariko Gorge/Lantern Cave/First Chest"},
	[BASE + 232] = {"@Eldin Region/Kakariko Gorge/Lantern Cave/Second Chest"},
	[BASE + 230] = {"@Eldin Region/Kakariko Gorge/Lantern Cave/Lantern Chest"},
	[BASE + 246] = {"@Eldin Region/Kakariko Gorge/Stone Pillars/Spire Heart Piece"},
	[BASE + 240] = {"@Eldin Region/Kakariko Gorge/Stone Pillars/Double Clawshot Chest"},
	[BASE + 244] = {"@Eldin Region/Kakariko Gorge/Owl Statue/Sky Character"},
	[BASE + 243] = {"@Eldin Region/Kakariko Gorge/Owl Statue/Chest"},
	[BASE + 231] = {"@Eldin Region/Kakariko Gorge Poes/Lantern Cave Poe/"},
	[BASE + 245] = {"@Eldin Region/Kakariko Gorge Poes/Kakariko Gorge Poe/"},
	[BASE + 242] = {"@Eldin Region/Kakariko Gorge Bugs/Male Pill Bug/"},
	[BASE + 241] = {"@Eldin Region/Kakariko Gorge Bugs/Female Pill Bug/"},
	
	--Lake Hylia Locations
	[BASE + 386] = {"@Lanayru Region/Lake Hylia/Owl Statue/Sky Character"},
	[BASE + 385] = {"@Lanayru Region/Lake Hylia/Owl Statue/Chest"},
	[BASE + 387] = {"@Lanayru Region/Lake Hylia/Vines Chest/"},
	[BASE + 381] = {"@Lanayru Region/Lake Hylia/Bubble Grotto/Cliff Chest"},
	[BASE + 380] = {"@Lanayru Region/Lake Hylia/Bubble Grotto/Bubble Grotto Chest"},
	[BASE + 438] = {"@Lanayru Region/Lake Hylia/Plumm Fruit Balloon Minigame/"},
	[BASE + 389] = {"@Lanayru Region/Lake Hylia/Shell Blade Grotto Chest/"},
	[BASE + 369] = {"@Lanayru Region/Lake Hylia/Flight By Fowl Minigame/Spinning Platform"},
	[BASE + 367] = {"@Lanayru Region/Lake Hylia/Flight By Fowl Minigame/Highest Platform"},
	[BASE + 368] = {"@Lanayru Region/Lake Hylia/Flight By Fowl Minigame/2nd Highest Platform"},
	[BASE + 365] = {"@Lanayru Region/Lake Hylia/Flight By Fowl Minigame/2nd Lowest Platform"},
	[BASE + 364] = {"@Lanayru Region/Lake Hylia/Flight By Fowl Minigame/Lowest Platform"},
	[BASE + 357] = {"@Lanayru Region/Lake Hylia/Auru Gift To Fyer/"},
	[BASE + 392] = {"@Lanayru Region/Lake Hylia/Water Toadpoli Grotto Chest/"},
	[BASE + 398] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/1st Chest"},
	[BASE + 403] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/2nd Chest"},
	[BASE + 408] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/3rd Chest"},
	[BASE + 401] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/4th Chest"},
	[BASE + 396] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/5th Chest"},
	[BASE + 406] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/6th Chest - Lantern"},
	[BASE + 405] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/7th Chest"},
	[BASE + 393] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/8th Chest"},
	[BASE + 402] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/9th Chest"},
	[BASE + 407] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/10th Chest"},
	[BASE + 394] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/11th Chest"},
	[BASE + 410] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/12th Chest"},
	[BASE + 409] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/13th Chest"},
	[BASE + 400] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/14th Chest"},
	[BASE + 395] = {"@Lanayru Region/Lake Hylia/Lake Lantern Cave/End Lantern Chest"},
	[BASE + 391] = {"@Lanayru Region/Lake Hylia/Underwater Chest/"},
	[BASE + 428] = {"@Lanayru Region/Lake Hylia/Left Statue Chest/"},
	[BASE + 429] = {"@Lanayru Region/Lake Hylia/Right Statue Chest/"},
	[BASE + 424] = {"@Lanayru Region/Lake Hylia/Lanayru Spring/Underwater Left Chest"},
	[BASE + 425] = {"@Lanayru Region/Lake Hylia/Lanayru Spring/Underwater Right Chest"},
	[BASE + 421] = {"@Lanayru Region/Lake Hylia/Lanayru Spring/Back Room Left Chest"},
	[BASE + 422] = {"@Lanayru Region/Lake Hylia/Lanayru Spring/Back Room Right Chest"},
	[BASE + 420] = {"@Lanayru Region/Lake Hylia/Lanayru Spring/Back Room Lantern Chest"},
	[BASE + 426] = {"@Lanayru Region/Lake Hylia/Lanayru Spring/West Double Clawshot Chest"},
	[BASE + 423] = {"@Lanayru Region/Lake Hylia/Lanayru Spring/East Double Clawshot Chest"},
	[BASE + 382] = {"@Lanayru Region/Lake Hylia Poes/Lake Hylia Bridge Cliff Poe/"},
	[BASE + 388] = {"@Lanayru Region/Lake Hylia Poes/Dock Poe/"},
	[BASE + 366] = {"@Lanayru Region/Lake Hylia Poes/Grotto Ledge Poe/"},
	[BASE + 373] = {"@Lanayru Region/Lake Hylia Poes/Isle of Riches Poe/"},
	[BASE + 390] = {"@Lanayru Region/Lake Hylia Poes/Tower Poe/"},
	[BASE + 399] = {"@Lanayru Region/Lake Hylia Poes/Lake Lantern Cave/1st Poe"},
	[BASE + 404] = {"@Lanayru Region/Lake Hylia Poes/Lake Lantern Cave/2nd Poe"},
	[BASE + 397] = {"@Lanayru Region/Lake Hylia Poes/Lake Lantern Cave/Final Poe"},
	[BASE + 379] = {"@Lanayru Region/Lake Hylia Poes/Alcove Poe/"},
	[BASE + 384] = {"@Lanayru Region/Lake Hylia Bugs/Male Mantis/"},
	[BASE + 383] = {"@Lanayru Region/Lake Hylia Bugs/Female Mantis/"},
	--[BASE + ] = {"@Lanayru Region/Lake Hylia Golden Wolves/Gerudo Desert Stone/"},
	
	--Lanayru Field Locations
	[BASE + 418] = {"@Lanayru Region/Lanayru Field/Spinner Track Chest/"},
	[BASE + 411] = {"@Lanayru Region/Lanayru Field/Behind Gate Underwater Chest/"},
	[BASE + 417] = {"@Lanayru Region/Lanayru Field/Skulltula Grotto Chest/"},
	[BASE + 419] = {"@Lanayru Region/Lanayru Field/Ice Block Puzzle Cave Chest/"},
	[BASE + 412] = {"@Lanayru Region/Lanayru Field Poes/Bridge Poe/"},
	[BASE + 415] = {"@Lanayru Region/Lanayru Field Poes/Grotto/Left Poe"},
	[BASE + 416] = {"@Lanayru Region/Lanayru Field Poes/Grotto/Right Poe"},
	[BASE + 413] = {"@Lanayru Region/Lanayru Field Bugs/Female Stag Beetle/"},
	[BASE + 414] = {"@Lanayru Region/Lanayru Field Bugs/Male Stag Beetle/"},
	
	--Ordon Locations
	[BASE + 464] = {"@Ordon/Link's House/Wooden Sword Chest"},
	[BASE + 456] = {"@Ordon/Link's House/Basement Chest"},
	[BASE + 463] = {"@Ordon/Rusl's House/Uli Cradle Delivery"},
	[BASE + 461] = {"@Ordon/Rusl's House/Ordon Sword"},
	[BASE + 462] = {"@Ordon/Sera's Shop/Sera Shop Slingshot"},
	[BASE + 457] = {"@Ordon/Sera's Shop/Ordon Cat Rescue"},
	[BASE + 459] = {"@Ordon/Ordon Shield/"},
	[BASE + 465] = {"@Ordon/Wrestling With Bo/"},
	[BASE + 455] = {"@Ordon/Herding Goats Reward/"},
	[BASE + 458] = {"@Ordon/Ranch Grotto Lantern Chest/"},
	[BASE + 460] = {"@Ordon Golden Wolves/Golden Wolf/"},
	
	--Sacred Grove Locations
	[BASE + 293] = {"@Sacred Grove/Pedestal/Master Sword"},
	[BASE + 294] = {"@Sacred Grove/Pedestal/Shadow Crystal"},
	[BASE + 292] = {"@Sacred Grove/Past Owl Statue Chest/"},
	[BASE + 295] = {"@Sacred Grove/Spinner Chest/"},
	[BASE + 288] = {"@Sacred Grove/Baba Serpent Grotto Chest/"},
	[BASE + 285] = {"@Sacred Grove/Lost Woods Lantern Chest/"},
	[BASE + 291] = {"@Sacred Grove Poes/Master Sword Poe/"},
	[BASE + 296] = {"@Sacred Grove Poes/Past Owl Statue Poe/"},
	[BASE + 284] = {"@Sacred Grove Poes/Lost Woods Boulder Poe/"},
	[BASE + 286] = {"@Sacred Grove Poes/Lost Woods Waterfall Poe/"},
	[BASE + 290] = {"@Sacred Grove Bugs/Bugs/Present - Male Snail"},
	[BASE + 289] = {"@Sacred Grove Bugs/Bugs/Past - Female Snail"},
	
	--Snowpeak Mountain Locations
	[BASE + 466] = {"@Snowpeak Mountain/Ashei Sketch/"},
	[BASE + 472] = {"@Snowpeak Mountain/Freezard Grotto Chest/"},
	[BASE + 470] = {"@Snowpeak Mountain/Cave Ice Lantern Chest/"},
	[BASE + 467] = {"@Snowpeak Mountain/Snowboard Racing Prize/"},
	[BASE + 468] = {"@Snowpeak Mountain Poes/Above Freezard Grotto Poe/"},
	[BASE + 469] = {"@Snowpeak Mountain Poes/Blizzard Poe/"},
	[BASE + 474] = {"@Snowpeak Mountain Poes/Poe Among Trees/"},
	[BASE + 471] = {"@Snowpeak Mountain Poes/Cave Ice Poe/"},
	[BASE + 473] = {"@Snowpeak Mountain Poes/Icy Summit Poe/"},
	--[BASE + ] = {"@Snowpeak Mountain Golden Wolves/Kakariko Graveyard Stone/"},
	
	--South Castle Town Locations
	[BASE + 436] = {"@Lanayru Region/South Castle Town/Tektite Grotto Chest/"},
	[BASE + 437] = {"@Lanayru Region/South Castle Town/Tightrope Chest/"},
	[BASE + 432] = {"@Lanayru Region/South Castle Town/Fountain Chest/"},
	[BASE + 430] = {"@Lanayru Region/South Castle Town/Double Clawshot Chasm Chest/"},
	--[BASE + ] = {"@Lanayru Region/South Castle Town/Wooden Statue/"},
	[BASE + 435] = {"@Lanayru Region/South Castle Town Poes/Outside South Castle Town Poe/"},
	[BASE + 431] = {"@Lanayru Region/South Castle Town Bugs/Female Ladybug/"},
	[BASE + 434] = {"@Lanayru Region/South Castle Town Bugs/Male Ladybug/"},
	[BASE + 433] = {"@Lanayru Region/South Castle Town Golden Wolves/Golden Wolf/"},
	
	--Upper Zora's River Locations
	[BASE + 374] = {"@Lanayru Region/Upper Zora's River/Iza/Helping Hand"},
	[BASE + 375] = {"@Lanayru Region/Upper Zora's River/Iza/Raging Rapids Minigame"},
	[BASE + 362] = {"@Lanayru Region/Upper Zora's River/Fishing Hole Bottle/"},
	[BASE + 363] = {"@Lanayru Region/Upper Zora's River/Fishing Hole Heart Piece/"},
	[BASE + 442] = {"@Lanayru Region/Upper Zora's River Poes/Upper Zora's River Poe/"},
	[BASE + 441] = {"@Lanayru Region/Upper Zora's River Bugs/Female Dragonfly/"},
	--[BASE + ] = {"@Lanayru Region/Upper Zora's River Golden Wolves/West Castle Town Stone/"},
	
	--Zora's Domain Locations
	[BASE + 447] = {"@Lanayru Region/Zora's Domain/Chest Behind Waterfall/"},
	[BASE + 448] = {"@Lanayru Region/Zora's Domain/Chest By Mother and Child Isles/"},
	[BASE + 453] = {"@Lanayru Region/Zora's Domain/Underwater Goron/"},
	[BASE + 450] = {"@Lanayru Region/Zora's Domain/Light All Torches Chest/"},
	[BASE + 449] = {"@Lanayru Region/Zora's Domain/Extinguish All Torches Chest/"},
	[BASE + 452] = {"@Lanayru Region/Zora's Domain Poes/Mother and Child Isle Poe/"},
	[BASE + 454] = {"@Lanayru Region/Zora's Domain Poes/Waterfall Poe/"},
	[BASE + 451] = {"@Lanayru Region/Zora's Domain Bugs/Male Dragonfly/"}
}