SERVER_COPY = {
	"Death Mountain Stone",
    "Zora River Stone",
    "Sacred Grove Stone",
    "Lake Hylia Stone",
    "Snowpeak Stone",
    "Hidden Village Stone",
    "Youth Scent",
    "Ilias Scent",
    "Medicine Scent",
    "ReekFish Scent",
    "Poe Scent",
    "Renados letter",
    "Telmas Invoice",
    "Wooden Statue",
    "Ilias Charm",
    "Memory Reward",
    "Current Region",
    "Diababa Defeated",
    "Fyrus Defeated",
    "Morpheel Defeated",
    "Stallord Defeated",
    "Blizzeta Defeated",
    "Armogohma Defeated",
    "Argorok Defeated",
    "Zant Defeated",
    "Current Stage",
    "Current Room",
    "Current Floor"
}