declare const classNames: {
    readonly permalinkInput: 'permalinkInput';
    readonly optionsPage: 'optionsPage';
    readonly logicAndPermalink: 'logicAndPermalink';
    readonly logicChooser: 'logicChooser';
    readonly plaintextLogicInput: 'plaintextLogicInput';
    readonly permalinkChooser: 'permalinkChooser';
    readonly launchButtons: 'launchButtons';
    readonly continueButton: 'continueButton';
    readonly counters: 'counters';
    readonly presetButton: 'presetButton';
    readonly optionsTooltip: 'optionsTooltip';
    readonly bold: 'bold';
    readonly optionsCategory: 'optionsCategory';
    readonly optionsTab: 'optionsTab';
    readonly checkboxOption: 'checkboxOption';
    readonly optionsBadRemote: 'optionsBadRemote';
    readonly splashScreen: 'splashScreen';
    readonly splashContent: 'splashContent';
    readonly splashError: 'splashError';
    readonly splashStatus: 'splashStatus';
    readonly loadingSpinner: 'loadingSpinner';
    readonly spinnerIcon: 'spinnerIcon';
};
export = classNames;
